"""criando tabela de fechamentos

Revision ID: 3f4b7689d9b4
Revises: 
Create Date: 2025-11-12 23:25:01.804168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f4b7689d9b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fechamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=200), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('preco_unitario', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cor', sa.String(length=100), nullable=True),
    sa.Column('desconto', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valor_sem_desconto', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valor_final', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fechamentos')
    # ### end Alembic commands ###
